
export const categories = [
  { id: 1, name: "জাতীয়", slug: "national" },
  { id: 2, name: "রাজনীতি", slug: "politics" },
  { id: 3, name: "আন্তর্জাতিক", slug: "international" },
  { id: 4, name: "খেলা", slug: "sports" },
  { id: 5, name: "বিনোদন", slug: "entertainment" },
  { id: 6, name: "লাইফস্টাইল", slug: "lifestyle" },
  { id: 7, name: "তথ্যপ্রযুক্তি", slug: "technology" },
  { id: 8, name: "অর্থনীতি", slug: "economics" },
];

export const mockNews = [
  {
    id: 1,
    title: "বাংলাদেশের অর্থনৈতিক প্রবৃদ্ধি নিয়ে নতুন প্রতিবেদন",
    summary: "বিশ্বব্যাংকের সর্বশেষ প্রতিবেদন অনুযায়ী বাংলাদেশের অর্থনীতি ইতিবাচক দিকে এগোচ্ছে। তবে কিছু চ্যালেঞ্জ এখনো রয়ে গেছে।",
    content: "এখানে বিস্তারিত সংবাদ থাকবে। বাংলাদেশের অর্থনীতির বর্তমান অবস্থা এবং ভবিষ্যতে করণীয় নিয়ে বিশেষজ্ঞরা তাদের মতামত দিয়েছেন...",
    category: "অর্থনীতি",
    slug: "economy-growth-report",
    image: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?q=80&w=1000&auto=format&fit=crop",
    author: "নিজস্ব প্রতিবেদক",
    date: "২০২৪-০২-১৩",
    time: "১০:৩০ এএম",
    isBreaking: true,
    isTrending: true,
  },
  {
    id: 2,
    title: "ক্রিকেট বিশ্বকাপে বাংলাদেশের বড় জয়",
    summary: "অসাধারণ নৈপুণ্য প্রদর্শন করে বাংলাদেশ দল শক্তিশালী প্রতিপক্ষকে পরাজিত করেছে। এটি দলের জন্য একটি বড় অর্জন।",
    content: "ক্রিকেট মাঠের উত্তেজনা এবং খেলোয়াড়দের ব্যক্তিগত পারফরম্যান্স নিয়ে এই প্রতিবেদনে বিস্তারিত আলোচনা করা হয়েছে।",
    category: "খেলা",
    slug: "bangladesh-big-win-cricket",
    image: "https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?q=80&w=1000&auto=format&fit=crop",
    author: "ক্রীড়া প্রতিবেদক",
    date: "২০২৪-০২-১৩",
    time: "০৯:১৫ এএম",
    isBreaking: false,
    isTrending: true,
  },
  {
    id: 3,
    title: "রাজধানীতে নতুন মেট্রোরেল স্টেশনের উদ্বোধন",
    summary: "যাত্রীসেবা আরও সহজ করতে আজ নতুন একটি স্টেশনের যাত্রা শুরু হলো। এতে যাতায়াতে সময় কমবে।",
    category: "জাতীয়",
    slug: "new-metro-station-inauguration",
    image: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?q=80&w=1000&auto=format&fit=crop",
    author: "নিজস্ব প্রতিবেদক",
    date: "২০২৪-০২-১২",
    time: "০৪:৪৫ পিএম",
    isBreaking: true,
    isTrending: false,
  },
  {
    id: 4,
    title: "নাসার নতুন অভিযানে নতুন গ্রহের সন্ধান",
    summary: "মহাকাশ গবেষণায় এক নতুন দিগন্ত উন্মোচিত হয়েছে। বিজ্ঞানীরা বাসযোগ্য নতুন একটি গ্রহের খোঁজ পেয়েছেন।",
    category: "আন্তর্জাতিক",
    slug: "nasa-new-planet-discovery",
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1000&auto=format&fit=crop",
    author: "বিজ্ঞান ও প্রযুক্তি ডেস্ক",
    date: "২০২৪-০২-১২",
    time: "১১:০০ পিএম",
    isBreaking: false,
    isTrending: true,
  },
  {
    id: 5,
    title: "ঢালিউডে নতুন ছবির শুভ মহরত",
    summary: "জনপ্রিয় তারকাদের অংশগ্রহণে আজ নতুন একটি সিনেমার শুটিং শুরু হয়েছে। ভক্তদের মধ্যে ব্যাপক উৎসাহ দেখা যাচ্ছে।",
    category: "বিনোদন",
    slug: "new-movie-inauguration-dhallywood",
    image: "https://images.unsplash.com/photo-1485846234645-a62644f84728?q=80&w=1000&auto=format&fit=crop",
    author: "বিনোদন প্রতিবেদক",
    date: "২০২৪-০২-১৩",
    time: "০২:৩০ পিএম",
    isBreaking: false,
    isTrending: false,
  },
  {
    id: 6,
    title: "শীতকালে ত্বকের যত্নে কিছু প্রয়োজনীয় টিপস",
    summary: "ত্বক শুষ্ক হয়ে যাওয়া থেকে বাঁচতে কি কি করবেন? চর্মরোগ বিশেষজ্ঞরা দিয়েছেন বিশেষ পরামর্শ।",
    category: "লাইফস্টাইল",
    slug: "winter-skin-care-tips",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=1000&auto=format&fit=crop",
    author: "স্বাস্থ্য ডেস্ক",
    date: "২০২৪-০২-১৩",
    time: "০৮:০০ এএম",
    isBreaking: false,
    isTrending: false,
  },
];
